version: '3.0'

services:
  heaven:
    build: heaven
    ports:
    - "3000:3000"
    restart: always

  hell:
    build: hell
    ports:
    - "8080:8080"
    links:
    - database
    - redis-server
    restart: always

  redis-server:
    image: redis
    ports:
    - "6379:6379"

  database:
    container_name: mongo
    image: mongo
    ports:
    - "27017:27017"
    environment: 
      MONGO_INITDB_DATABASE: "sih_platform"
      MONGODB_USER: "${db_user}"
      MONGODB_PASS: "${db_pass}"
